Yuu developer patch 3
yuu-developer/TypeLearnEnglish pull request #3
Opened 2024-04-25 05:03 UTC by yuu-developer

ER図を追記しました。

2024-04-25 11:54 UTC, tarakish reviewed
ご提出ありがとうございます。
ER図の変更履歴を残しながら、やり取りを行いたいため、コメント欄に作成したER図のスクリーンショットを掲載していただけますでしょうか。（Gyazo・マークダウン）

2024-04-25 13:41 UTC, yuu-developer commented
> ご提出ありがとうございます。 ER図の変更履歴を残しながら、やり取りを行いたいため、コメント欄に作成したER図のスクリーンショットを掲載していただけますでしょうか。（Gyazo・マークダウン）

ご返信ありがとうございます。承知いたしました。
よろしくお願いいたします。

[![Image from Gyazo](https://i.gyazo.com/442335590a7a924fd654d6f1abde52a7.png)](https://gyazo.com/442335590a7a924fd654d6f1abde52a7)

2024-04-26 03:23 UTC, kenchasonakai commented
テーブル名から何を行いたいのかを推測が難しかったので各テーブルと各カラムについてそれぞれどんなデータを入れるためのテーブル・カラムなのかの説明をこのプルリクエストのコメントに書いていただけますでしょうか？

2024-04-26 08:12 UTC, yuu-developer commented
> テーブル名から何を行いたいのかを推測が難しかったので各テーブルと各カラムについてそれぞれどんなデータを入れるためのテーブル・カラムなのかの説明をこのプルリクエストのコメントに書いていただけますでしょうか？

以下テーブル名とカラムについての説明になります。
ご確認のほど、よろしくお願いいたします。

### **User**

ユーザーの認証、識別、および個人設定へのアクセスを提供。各ユーザーの基本的な情報とログイン情報を保持します。

- **username**: 名前。
- **email**: メールアドレス
- **crypted_password**: パスワード

### **UserProfiles**

ユーザーの詳細情報を管理。個々のユーザーに関連する詳細なプロフィール情報を提供します。

- **user_id (FK)**: どのユーザーに属しているかを示すための外部キー。テーブルと直接関連付け。
- introduction: 自己紹介文。
- **avatar**: プロフィール画像。
- **preferences**: ユーザーの設定。

### **Sessions**

ユーザーのセッションデータを管理。ユーザーのアクティビティを記録します。

- **user_id (FK)**: どのユーザーのセッションであるかを示す外部キー。
- **article_id (FK)**: セッション中に利用される英文のID。
- **start_time** / **end_time**: セッションの開始および終了時刻。
- **score**: セッションで得られたスコア。
- **difficulty_level**: セッションの難易度。

### **Articles**

アプリケーションで使用する英文の内容を保持します。

- **content**: 英文の内容。
- **translation**: 英文の日本語訳。
- **grammar_explanation**: 文法説明。

### **Words**

語彙の管理。使用される単語の定義、使用例を保存します。

- **text**: 単語のテキスト。
- **definition**: 単語の定義。
- **example_usage**: 単語の使用例。

### **Progresses**

ユーザーの進捗と成果を追跡。学習進捗と成果を日付ごとに記録します。

- **user_id (FK)**: どのユーザーの進捗であるかを示す外部キー。
- **date**: 進捗が記録された日付。
- **cumulative_score**: 累積スコア。

### **MultiplayerGames**

マルチプレイヤーゲームセッションを管理。複数のユーザーが同時に参加するゲームのデータを保持します.

- **session_id1 (FK)** / **session_id2 (FK)**: ゲームに参加する2つのセッションのID。。
- **start_time** / **end_time**: ゲームの開始と終了時刻。
- **winner_user_id (FK)**: ゲームの勝者のユーザーID。

### **GuestSessions**

ゲストユーザーの一時的なセッションデータを管理。

- **session_data**: ゲストユーザーのセッション中に発生したデータの一時的保存。
- **created_at**: セッションが作成された日時を記録。セッションの有効期限のため。

2024-04-27 05:56 UTC, tarakish reviewed
ご説明ありがとうございます。わかりやすくなりました👍
以下コメントです！

---

- UserProfiles
  - preferences: ユーザーの設定とありますが、具体的にどのような値が入るものですか？
  - できればカラム名からどのような値が入るものなのか推測できる命名に修正できると良いです。

- Sessions
  - 現在のarticleとの関連付けでは1セッション中に一つの英文のみが紐づけられるようになっていますが、正しいかどうかご確認いただけますか？
  - dificulty_levelはsessionにあってもよいですが、難易度によって英文を出し分けるのであれば少なくともarticles、wordsの方にも必要かと思いました。

- Words
  - 単語の使用例は一つだけ設定できる想定でしょうか？

- Progresses
  - 累積スコアとはその日のものなのか、すべての日付のものなのかどちらでしょうか？

一旦上記をご確認お願いします！

2024-04-27 08:44 UTC, yuu-developer commented
> ご説明ありがとうございます。わかりやすくなりました👍 以下コメントです！
> 
> * UserProfiles
>   
>   * preferences: ユーザーの設定とありますが、具体的にどのような値が入るものですか？
>   * できればカラム名からどのような値が入るものなのか推測できる命名に修正できると良いです。
> * Sessions
>   
>   * 現在のarticleとの関連付けでは1セッション中に一つの英文のみが紐づけられるようになっていますが、正しいかどうかご確認いただけますか？
>   * dificulty_levelはsessionにあってもよいですが、難易度によって英文を出し分けるのであれば少なくともarticles、wordsの方にも必要かと思いました。
> * Words
>   
>   * 単語の使用例は一つだけ設定できる想定でしょうか？
> * Progresses
>   
>   * 累積スコアとはその日のものなのか、すべての日付のものなのかどちらでしょうか？
> 
> 一旦上記をご確認お願いします！

お忙しいところご指導ありがとうございます。

UserProfiles

- preferences: ユーザーの設定とありますが、具体的にどのような値が入るものですか？
- できればカラム名からどのような値が入るものなのか推測できる命名に修正できると良いです。

→preferencesは各ユーザーがアプリケーションの背景カラーやフォントサイズを調整するための設定を考えていましたが、必ず必要ではないため今回は削除させていただきます

Sessions

- 現在のarticleとの関連付けでは1セッション中に一つの英文のみが紐づけられるようになっていますが、正しいかどうかご確認いただけますか？

→すみません、中間テーブルを作成する必要がありました。

- dificulty_levelはsessionにあってもよいですが、難易度によって英文を出し分けるのであれば少なくともarticles、wordsの方にも必要かと思いました。

→dificulty_levelはarticles、wordsに必要でしたので追加しました。

Words

- 単語の使用例は一つだけ設定できる想定でしょうか？

→単語の使用例を複数持つことができる方が良いと判断したため、変更しました。

Progresses

- 累積スコアとはその日のものなのか、すべての日付のものなのかどちらでしょうか？

累積スコアはすべての日付のもので考えていました。日ごとのスコアとしてdaily_scoreを追加しました。また、累計スコアはtotal_scoreへとカラム名を変更しました。

2024-04-27 08:47 UTC, yuu-developer commented
以下新しいER図と変更内容についてまとめました。ご指導お願いいたします！

### **User**

ユーザーの認証、識別、および個人設定へのアクセスを提供。各ユーザーの基本的な情報とログイン情報を保持します。

- **username**: 名前。
- **email**: メールアドレス
- **crypted_password**: パスワード

### **UserProfiles**

ユーザーの詳細情報を管理。個々のユーザーに関連する詳細なプロフィール情報を提供します。

- **user_id (FK)**: どのユーザーに属しているかを示すための外部キー。テーブルと直接関連付け。
- introduction: 自己紹介文。
- **avatar**: プロフィール画像。

### **Sessions**

ユーザーのセッションデータを管理。ユーザーのアクティビティを記録します。

- **user_id (FK)**: どのユーザーのセッションであるかを示す外部キー。
- **start_time** / **end_time**: セッションの開始および終了時刻。
- **score**: セッションで得られたスコア。
- **difficulty_level**: 難易度。

### **Articles**

アプリケーションで使用する英文の内容を保持します。

- **content**: 英文の内容。
- **translation**: 英文の日本語訳。
- **grammar_explanation**: 文法説明。
- **difficulty_level**: 難易度。

### **SessionArticles**

ユーザーがセッション中に複数の英文を扱うための設計。

- **session_id** (FK):どのセッションに関連する英文かを示す外部キー。
- **article_id**(FK):セッション中に使用される英文を特定する外部キー。

### **Words**

語彙の管理。使用される単語の定義

- **text**: 単語のテキスト。
- **definition**: 単語の定義。
- **difficulty_level**: 難易度。

### **WordUsages**

各単語の例を複数持てるように。

- **word_id** (FK):どの単語に対する使用例かを示します。
- **usage_example :具体的な例文を保持します**

### **Progresses**

ユーザーの進捗と成果を追跡。学習進捗と成果を日付ごとに記録します。

- **user_id (FK)**: どのユーザーの進捗であるかを示す外部キー。
- **date**: 進捗が記録された日付。
- **daily_score:日ごとのスコア。**
- **total_score**: 累積スコア。

### **MultiplayerGames**

マルチプレイヤーゲームセッションを管理。複数のユーザーが同時に参加するゲームのデータを保持します.

- **session_id1 (FK)** / **session_id2 (FK)**: ゲームに参加する2つのセッションのID。。
- **start_time** / **end_time**: ゲームの開始と終了時刻。
- **winner_user_id (FK)**: ゲームの勝者のユーザーID。

### **GuestSessions**

ゲストユーザーの一時的なセッションデータを管理。

- **session_data**: ゲストユーザーのセッション中に発生したデータの一時的保存。
- **created_at**: セッションが作成された日時を記録。セッションの有効期限のため。

[![Image from Gyazo](https://i.gyazo.com/36a86ed607092743801992695070f9a2.png)](https://gyazo.com/36a86ed607092743801992695070f9a2)

2024-04-28 04:49 UTC, tarakish requested changes
ご対応ありがとうございます。確認しました。
- 一部説明とER図のカラム名が違う箇所があるので見直しをお願いします。
- 各カラムについてデータ型も記載するように修正をお願いします！

2024-04-28 05:39 UTC, yuu-developer commented
> ご対応ありがとうございます。確認しました。
> 
> * 一部説明とER図のカラム名が違う箇所があるので見直しをお願いします。
> * 各カラムについてデータ型も記載するように修正をお願いします！

ご指導ありがとうございます。
以下修正内容です。
dairy_score → daily_score

データ型も記載しました。
ご確認のほどよろしくお願いいたします。

[![Image from Gyazo](https://i.gyazo.com/2df60782b52fee422485b8401498e891.png)](https://gyazo.com/2df60782b52fee422485b8401498e891)

2024-04-30 02:35 UTC, tmtkzk0823 commented
修正ありがとうございます。
以下、追加のコメントです。

---

### 全体
- こちらのER図において ,`Session`とはどのような意味で使用されていますか？通常の意味とは異なるように感じたので、お手数ですがご説明をお願いします。

### Usersテーブル
- `username`というカラムがありますが、こちら`name`のみで良さそうに思いました。

### Words、Articlesテーブル
- リレーションの線を見ると 多：多 になっているかと思います。この場合は中間テーブルを用意したほうがいいかと思います。また、リレーションが、現状であっているのか確認をお願いします。

2024-04-30 04:58 UTC, yuu-developer commented
> 修正ありがとうございます。 以下、追加のコメントです。
> 
> ### 全体
> * こちらのER図において ,`Session`とはどのような意味で使用されていますか？通常の意味とは異なるように感じたので、お手数ですがご説明をお願いします。
> 
> ### Usersテーブル
> * `username`というカラムがありますが、こちら`name`のみで良さそうに思いました。
> 
> ### Words、Articlesテーブル
> * リレーションの線を見ると 多：多 になっているかと思います。この場合は中間テーブルを用意したほうがいいかと思います。また、リレーションが、現状であっているのか確認をお願いします。

### 全体

- Sessionの意味について

ユーザーがアプリケーション内で行う学習活動の一連の期間(アクティビティの開始と終了時刻、スコア表示、難易度選択)という意味合いで使用しました。代替案としては『Actives』、『Studies』、『Practices』などのテーブル名を考えています。

### Usersテーブル

- usernameをnameに修正しました。

### Words、Articlesテーブル

- リレーションを全て確認したところ、ご指摘頂いたところに中間テーブルが必要でしたので修正しました。

2024-04-30 05:05 UTC, yuu-developer commented
以下修正後のER図と各テーブル、カラムの説明になります。
ご確認のほど、よろしくお願いいたします。
[![Image from Gyazo](https://i.gyazo.com/f5f75c977041e9c3aaa0fe3f094a26c3.png)](https://gyazo.com/f5f75c977041e9c3aaa0fe3f094a26c3)

### **Users**

ユーザーの認証、識別、および個人設定へのアクセスを提供。各ユーザーの基本的な情報とログイン情報を保持します。

- **name**: 名前。
- **email**: メールアドレス
- **crypted_password**: パスワード

### **UserProfiles**

ユーザーの詳細情報を管理。個々のユーザーに関連する詳細なプロフィール情報を提供します。

- **user_id (FK)**: どのユーザーに属しているかを示すための外部キー。
- introduction: 自己紹介文。
- **avatar**: プロフィール画像。

### **Sessions**

ユーザーのセッションデータを管理。ユーザーのアクティビティを記録します。

- **user_id (FK)**: どのユーザーのセッションであるかを示す外部キー。
- **start_time** / **end_time**: セッションの開始および終了時刻。
- **score**: セッションで得られたスコア。
- **difficulty_level**: 難易度。

### **Session_Articles**

ユーザーがセッション中に複数の英文を扱うための中間テーブル。

- **session_id** (FK):セッションを示す外部キー。
- **article_id**(FK):英文を特定する外部キー。

### **Articles**

アプリケーションで使用する英文の内容を保持します。

- **content**: 英文の内容。
- **translation**: 英文の日本語訳。
- **grammar_explanation**: 文法説明。
- **difficulty_level**: 難易度。

### **Word_Articles**

1単語を複数の英文に、1英文に複数の単語を使用できるための中間テーブル。

- **word_id** (FK):単語を示す外部キー。
- **article_id**(FK):英文を特定する外部キー。

### **Words**

語彙の管理。使用される単語の定義

- **text**: 単語のテキスト。
- **definition**: 単語の定義。
- **difficulty_level**: 難易度。

### **WordUsages**

各単語の例を複数持てるように。

- **word_id** (FK):どの単語に対する使用例かを示します。
- **usage_example :具体的な例文を保持します**

### **Progresses**

ユーザーの進捗と成果を追跡。学習進捗と成果を日付ごとに記録します。

- **user_id (FK)**: どのユーザーの進捗であるかを示す外部キー。
- **date**: 進捗が記録された日付。
- **daily_score:日ごとのスコア。**
- **total_score**: 累積スコア。

### **MultiplayerGames**

マルチプレイヤーゲームセッションを管理。複数のユーザーが同時に参加するゲームのデータを保持します.

- **session_id1 (FK)** / **session_id2 (FK)**: ゲームに参加する2つのセッションのID。。
- **start_time** / **end_time**: ゲームの開始と終了時刻。
- **winner_user_id (FK)**: ゲームの勝者のユーザーID。

### **GuestSessions**

ゲストユーザーの一時的なセッションデータを管理。

- **session_data**: ゲストユーザーのセッション中に発生したデータの一時的保存。
- **created_at**: セッションが作成された日時を記録。セッションの有効期限のため。

2024-05-02 01:08 UTC, tmtkzk0823 commented
修正、ご説明ありがとうございます。

---

> Sessionの意味について
ユーザーがアプリケーション内で行う学習活動の一連の期間(アクティビティの開始と終了時刻、スコア表示、難易度選択)という意味合いで使用しました。代替案としては『Actives』、『Studies』、『Practices』などのテーブル名を考えています。

上記の中ですと、「Practices」がいいかと思いますがいかがでしょうか？（Sessionsですと、様々な意味が予測でしてしまうため）

2024-05-02 01:56 UTC, yuu-developer commented
ご指導ありがとうございます。「Sessions」から「Practices」に変更しました。
以下修正したER図になります。
ご確認のほど、よろしくお願いいたします。
[![Image from Gyazo](https://i.gyazo.com/9059a2e9bca96ee55f242e82de6ca29b.png)](https://gyazo.com/9059a2e9bca96ee55f242e82de6ca29b)

### **Users**

ユーザーの認証、識別、および個人設定へのアクセスを提供。各ユーザーの基本的な情報とログイン情報を保持します。

- **name**: 名前。
- **email**: メールアドレス
- **crypted_password**: パスワード

### **UserProfiles**

ユーザーの詳細情報を管理。個々のユーザーに関連する詳細なプロフィール情報を提供します。

- **user_id (FK)**: どのユーザーに属しているかを示すための外部キー。
- introduction: 自己紹介文。
- **avatar**: プロフィール画像。

### Practices

ユーザーのタイピングデータを管理。ユーザーのアクティビティを記録します。

- **user_id (FK)**: どのユーザーのセッションであるかを示す外部キー。
- **start_time** / **end_time**: ゲームの開始および終了時刻。
- **score**: セッションで得られたスコア。
- **difficulty_level**: 難易度。

### Practice_Articles

複数の英文を扱うための中間テーブル。

- practice**_id** (FK):タイピングデータを示す外部キー。
- **article_id**(FK):英文を特定する外部キー。

### **Articles**

アプリケーションで使用する英文の内容を保持します。

- **content**: 英文の内容。
- **translation**: 英文の日本語訳。
- **grammar_explanation**: 文法説明。
- **difficulty_level**: 難易度。

### **Word_Articles**

1単語を複数の英文に、1英文に複数の単語を使用するための中間テーブル。

- **word_id** (FK):単語を示す外部キー。
- **article_id**(FK):英文を特定する外部キー。

### **Words**

語彙の管理。使用される単語の定義

- **text**: 単語のテキスト。
- **definition**: 単語の定義。
- **difficulty_level**: 難易度。

### **WordUsages**

各単語の例を複数持てるように。

- **word_id** (FK):どの単語に対する使用例かを示します。
- **usage_example :具体的な例文を保持します**

### **Progresses**

ユーザーの進捗と成果を追跡。学習進捗と成果を日付ごとに記録します。

- **user_id (FK)**: どのユーザーの進捗であるかを示す外部キー。
- **date**: 進捗が記録された日付。
- **daily_score:日ごとのスコア。**
- **total_score**: 累積スコア。

### **MultiplayerGames**

マルチプレイヤーゲームセッションを管理。複数のユーザーが同時に参加するゲームのデータを保持します.

- practice**_id1 (FK)** / practice**_id2 (FK)**: ゲームに参加する2つのpracticeID。
- **start_time** / **end_time**: ゲームの開始と終了時刻。
- **winner_user_id (FK)**: ゲームの勝者のユーザーID。

### **Guest**Practices

ゲストユーザーの一時的なタイピングデータを管理。

- practice**_data**: ゲストユーザーのタイピングデータの一時的保存。
- **created_at**: ゲスト作成された日時を記録。

2024-05-02 03:55 UTC, tmtkzk0823 commented
修正ありがとうございます！

LGTMです！

2024-05-17 05:25 UTC, merged